
[functions.send-booking-confirmation-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-booking-confirmation-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-booking-confirmation-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-booking-confirmation-email/*.html" ]

[functions.fetch-user-emails]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-user-emails/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-user-emails/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-user-emails/*.html" ]

[functions.manage-user-by-email]
enabled = true
verify_jwt = true
import_map = "./functions/manage-user-by-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/manage-user-by-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/manage-user-by-email/*.html" ]
